module.exports = [
    { type: 0, name: "with Axel" },
    { type: 0, name: "Tic Tac Toe" },
    { type: 0, name: "Hide & Go Seek" },
    { type: 3, name: "anime" },
    { type: 0, name: "with Shodan" },
    { type: 3, name: "ad infinitum" },
    { type: 4, name: "anime" },
    { type: 2, name: "Hip Hop" },
    { type: 2, name: "my Indie playlist" },
    { type: 0, name: "with a puzzle" },
    { type: 4, name: "streams" },
    { type: 3, name: "naughty things" },
    { type: 3, name: "the fish" },
    { type: 1, name: "in the bath" },
    { type: 1, name: "with my encryption" },
    { type: 4, name: "data to Git" },
    { type: 3, name: "Axel play games" },
    { type: 2, name: "Vampire Weekend" },
    { type: 2, name: "Big Sean's new album" },
    { type: 2, name: "Lil Wayne" },
    { type: 3, name: "TENET" },
    { type: 3, name: "RE:ZERO" },
    { type: 4, name: "Axel's cat Pepper" },
    { type: 4, name: "Axel's cat Salty" },
    { type: 3, name: "YmlyZSBQbmZmdnFs" },
    { type: 0, name: "Mondegreen" },
    { type: 0, name: "Cards Against Humanity" },
    { type: 2, name: "Childish Gambino" },
    { type: 0, name: "with Medusa" },
    { type: 2, name: "the Siren's song" }
];